# Generated by Django 2.1 on 2018-08-09 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_email', models.CharField(max_length=50)),
                ('user_phone', models.CharField(max_length=15)),
                ('user_country', models.CharField(max_length=20)),
                ('user_city', models.CharField(max_length=20)),
                ('user_state', models.CharField(max_length=50)),
                ('user_zip', models.CharField(max_length=10)),
                ('user_gender', models.CharField(max_length=8)),
                ('user_about', models.CharField(max_length=500)),
                ('user_image', models.ImageField(upload_to='')),
                ('user_creation_date', models.CharField(max_length=100)),
                ('user_info_last_update', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'tb_employee',
            },
        ),
    ]
