# Generated by Django 2.1.1 on 2018-10-16 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('village', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('zip', models.CharField(max_length=20, null=True)),
                ('country', models.CharField(max_length=30, null=True)),
            ],
            options={
                'db_table': 'AddressTable',
            },
        ),
        migrations.CreateModel(
            name='BirthdayTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.CharField(max_length=2)),
                ('birthmonth', models.CharField(max_length=2)),
                ('birthyear', models.CharField(max_length=4)),
            ],
            options={
                'db_table': 'BirthdayTable',
            },
        ),
        migrations.CreateModel(
            name='DeviceDetailsTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('current_os', models.CharField(max_length=200)),
                ('os_quality', models.CharField(max_length=100)),
                ('machine_type', models.CharField(max_length=100)),
                ('device_details', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'DeviceDetailsTable',
            },
        ),
        migrations.CreateModel(
            name='GenderTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'GenderTable',
            },
        ),
        migrations.CreateModel(
            name='MessageTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=3000, null=True)),
            ],
            options={
                'db_table': 'MessageTable',
            },
        ),
        migrations.CreateModel(
            name='NameTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('slug_name', models.SlugField(max_length=200)),
            ],
            options={
                'db_table': 'NameTable',
            },
        ),
        migrations.CreateModel(
            name='PostTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(max_length=1000, null=True)),
                ('post_image', models.ImageField(null=True, upload_to='')),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(null=True)),
                ('slug_post', models.SlugField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'PostTable',
            },
        ),
        migrations.CreateModel(
            name='ProfilePhotoTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'ProfilePhotoTable',
            },
        ),
        migrations.CreateModel(
            name='ReactionTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.IntegerField(default=0)),
                ('comment', models.TextField(null=True)),
                ('post_tbl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BlogApp.PostTable')),
            ],
            options={
                'db_table': 'ReactionTable',
            },
        ),
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=50, null=True)),
                ('email_verification_code', models.CharField(max_length=10)),
                ('email_validity', models.IntegerField(default=0)),
                ('re_request_code', models.IntegerField(default=0, null=True)),
                ('password', models.CharField(max_length=30)),
                ('password_reset_code', models.IntegerField(null=True)),
                ('registered_on', models.DateField(auto_now_add=True)),
                ('user_activity', models.IntegerField(default=0)),
                ('profile_completion', models.IntegerField()),
                ('address_table', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BlogApp.AddressTable')),
                ('birthday_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BlogApp.BirthdayTable')),
                ('device_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BlogApp.DeviceDetailsTable')),
                ('gender_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BlogApp.GenderTable')),
                ('msg_tabl', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BlogApp.MessageTable')),
                ('name_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BlogApp.NameTable')),
                ('pp_table', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BlogApp.ProfilePhotoTable')),
            ],
            options={
                'db_table': 'UserTable',
            },
        ),
        migrations.AddField(
            model_name='posttable',
            name='post_table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BlogApp.UserTable'),
        ),
    ]
